name: Build and Release Fabric

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release (e.g. v1.3.0)'
        required: true
        default: 'v1.3.0'
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build All Fabric Versions
        run: ./gradlew :fabric:1.21.11:build :fabric:1.21.10:build :fabric:1.21.9:build :fabric:1.21.8:build :fabric:1.21.5:build :fabric:1.21.4:build :fabric:1.21.1:build :fabric:1.20.1:build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ inputs.tag_name || github.ref_name }}
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          files: fabric/versions/*/build/libs/*.jar
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
